ExUnit.start()

Code.require_file("support/weld_helpers/connectors_github_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/connectors_linear_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/connectors_notion_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_auth_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_brain_ingress_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_consumer_surfaces_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_contracts_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_control_plane_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_direct_runtime_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_dispatch_runtime_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_ingress_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_platform_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_policy_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_store_local_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_store_postgres_test_helper.exs", __DIR__)
Code.require_file("support/weld_helpers/core_webhook_router_test_helper.exs", __DIR__)
